CREATE TABLE IF NOT EXISTS products(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name varchar(100) NOT NULL,
    price DECIMAL(10,2) DEFAULT 0.00,
    photo VARCHAR(255) NOT NULL,
    description TEXT DEFAULT NULL,
    stock INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
) collate = utf8mb4_unicode_ci;